# Generated by Django 4.0.5 on 2022-06-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
